name: demo
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0-42.0.dev

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  async: ^2.11.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
